modLoader="javafml"
loaderVersion="[36,]"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Trample-No-More/issues"
license="LGPL v2.1"

[[mods]]
modId="tramplenomore"
updateJSONURL="https://updates.blamejared.com/get?n=tramplenomore&gv=1.16.5"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.tramplenomore]]
    modId="forge"
    mandatory=true
    versionRange="[36,]"
    ordering="NONE"
    side="SERVER"

[[dependencies.tramplenomore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="SERVER"