modLoader = "javafml"
license = "LGPL 2.1"
issueTrackerURL = "https://github.com/Darkhax-Minecraft/Trample-No-More/issues"

[[mods]]
modId = "tramplenomore"
version = "26.2.0.0"
displayName = "TrampleNoMore"
updateJSONURL = "https://updates.blamejared.com/get?n=tramplenomore&gv=26.2&ml=neoforge"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/trample-no-more"
logoFile = "logo_tramplenomore.png"
logoBlur = false
credits = "This project is made possible with Patreon support from players like you. Thank you! lothrazar, techsquirrel, Keyana , Darkosto, Tobias Ward, noobanidus"
authors = "Darkhax"
description = "Adds several ways to avoid trampling crops."

[[mixins]]
config = "tramplenomore.common.mixins.json"

[[mixins]]
config = "tramplenomore.neoforge.mixins.json"

[[dependencies.tramplenomore]]
modId = "minecraft"
type = "required"
versionRange = "26.2"
ordering = "NONE"
side = "BOTH"

[[dependencies.tramplenomore]]
modId = "neoforge"
type = "required"
versionRange = "[26.2.0.1-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tramplenomore]]
modId = "bookshelf"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tramplenomore]]
modId = "prickle"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

